FROM node:14-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./docker/config/nginx.conf /etc/nginx/nginx.conf
EXPOSE 90
CMD ["nginx", "-g", "daemon off;"]